#ifndef SAPLUGIN_GLOBAL_H
#define SAPLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SAPLUGIN_LIBRARY)
#  define SAPLUGINSHARED_EXPORT Q_DECL_EXPORT
#else
#  define SAPLUGINSHARED_EXPORT Q_DECL_IMPORT
#endif


#define HAOKE_SA_ORDER_STR "001"
#define HAOKE_SA_DELIVERY_STR "002"
#define HAOKE_SA_RETURNED_STR "003"
#define HAOKE_SA_RD_STR "004"

#define HAOKE_SA_SETTLE_STR "005"
#define HAOKE_SA_CONDELIVERY_STR "006"
#define HAOKE_SA_CONRETURNED_STR "007"
#define HAOKE_SA_CONSETTLE_STR "008"
#define HAOKE_SA_PRICE_STR "010"
#define HAOKE_SA_HRD_STR "011"
#define HAOKE_SA_CONRD_STR "012"
#define HAOKE_SA_HCONRD_STR "013"
#define HAOKE_SA_ORDERQUERY_STR "101"
#define HAOKE_SA_ORDEREXECQUERY_STR "103"
#define HAOKE_SA_DELIVERYQUERY_STR "121"
#define HAOKE_SA_RETURNEDQUERY_STR "123"
#define HAOKE_SA_RDQUERY_STR "141"
#define HAOKE_SA_SETTLEQUERY_STR "151"
#define HAOKE_SA_CON_DELIVERYQUERY_STR "161"
#define HAOKE_SA_CON_RETURNEDQUERY_STR "163"
#define HAOKE_SA_CON_SETTLEQUERY_STR "171"
#define HAOKE_SA_CUSTOMER_SUMMARY_STR "201"
#define HAOKE_SA_PURCHASE_SUMMARY_STR "202"
#define HAOKE_SA_SETTLE_DETAILE_STR "203"
#define HAOKE_SA_SETTLE_REMAIN_STR "204"
#define HAOKE_SA_SYSTEMSET_STR "301"

#endif // SAPLUGIN_GLOBAL_H
