#ifndef CGPLUGIN_GLOBAL_H
#define CGPLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CGPLUGIN_LIBRARY)
#  define CGPLUGINSHARED_EXPORT Q_DECL_EXPORT
#else
#  define CGPLUGINSHARED_EXPORT Q_DECL_IMPORT
#endif

#define HAOKE_PU_ORDER_STR "001"
#define HAOKE_PU_ARRIVAL_STR "002"
#define HAOKE_PU_RETURNED_STR "003"
#define HAOKE_PU_RD_STR "004"
#define HAOKE_PU_SETTLE_STR "005"
#define HAOKE_PU_BEGIN_RD_STR "006"
#define HAOKE_PU_ORDERQUERY_STR "101"
#define HAOKE_PU_ORDEREXECQUERY_STR "103"
#define HAOKE_PU_ARRIVALQUERY_STR "121"
#define HAOKE_PU_RETURNEDQUERY_STR "123"
#define HAOKE_PU_RDQUERY_STR "141"
#define HAOKE_PU_SETTLEQUERY_STR "151"
#define HAOKE_PU_SUPPLIE_SUMMARY_STR "201"
#define HAOKE_PU_PURCHASE_SUMMARY_STR "202"
#define HAOKE_PU_SETTLE_DETAILE_STR "203"
#define HAOKE_PU_SETTLE_REMAIN_STR "204"
#define HAOKE_PU_SYSTEMSET_STR "301"
#endif // CGPLUGIN_GLOBAL_H
