#ifndef WFAPLUGIN_GLOBAL_H
#define WFAPLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(WFAPLUGIN_LIBRARY)
#  define WFAPLUGINSHARED_EXPORT Q_DECL_EXPORT
#else
#  define WFAPLUGINSHARED_EXPORT Q_DECL_IMPORT
#endif


#define HAOKE_FA_AP_STR "001"
#define HAOKE_FA_AR_STR "002"
#define HAOKE_FA_AP_BILL_STR "003"
#define HAOKE_FA_AR_BILL_STR "004"
#define HAOKE_FA_BILL_ACCNT_STR "005"

#define HAOKE_FA_BILL_CANCEL_ACCNT_STR "006"
#define HAOKE_FA_SUBSIDIARY_STR "007"
#define HAOKE_FA_SUMMARY_STR "008"
#define HAOKE_FA_TRANSCEIVERS_SUMMARY_STR "009"

#define HAOKE_FA_AP_BILL_QUERY_STR "101"
#define HAOKE_FA_AR_BILL_QUERY_STR "103"
#define HAOKE_FA_COSTACCOUNT_SET_STR "301"
#define HAOKE_FA_KM_STR "302"
#endif // WFAPLUGIN_GLOBAL_H
